---
- hosts: host
  tasks:
    - name: Create empty swap file
      command: fallocate -l 512M /swapfile
      become: yes
    - name: Secure swap file
      command: chmod 600 /swapfile
      become: yes
    - name: Format swap file
      command: mkswap /swapfile
      become: yes
    - name: activate swap file
      command: swapon /swapfile
      become: yes
    - name: Include swap file
      lineinfile: dest=/etc/fstab state=present line="/swapfile none swap defaults 0 0"
      become: yes

