- hosts: hostName
  tasks:
  - include: apt_get_update.yaml
  - name: Install apt packages
    apt:
      pkg: "{{ item }}"
      state: latest
      force: yes
    register: install_packages
    until: install_packages|success
    sudo: yes
    with_items:
     - galera-3
     - galera-arbitrator-3
     - mysql-wsrep-5.6
     - python-mysqldb
