---
- hosts: admin
  vars_files:
    - vars/settings-default.yml
  tasks:
    - name: Apply ceph.conf
      template: src='src/ceph.conf' dest='{{ceph_dir}}/ceph.conf'
    - name: Add initial monitor
      shell: ceph-deploy mon create-initial
      args:
       chdir: "{{ceph_dir}}"
    - name: Copy configs to nodes
      shell: ceph-deploy admin {{item.hostname}}
      with_items: "{{mons + osds}}"
      args: 
       chdir: "{{ceph_dir}}"

